import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles } from "lucide-react";

const CODE_FRAMES = [
  {
    lines: [
      { indent: 0, tokens: [{ t: "kw", v: "import" }, { t: "plain", v: " { " }, { t: "id", v: "analyze" }, { t: "plain", v: " } " }, { t: "kw", v: "from" }, { t: "str", v: " './covai'" }] },
      { indent: 0, tokens: [] },
      { indent: 0, tokens: [{ t: "kw", v: "async function" }, { t: "fn", v: " runTests" }, { t: "plain", v: "(suite) {" }] },
      { indent: 1, tokens: [{ t: "cmt", v: "// 🤖 AI analyzing coverage..." }] },
      { indent: 1, tokens: [{ t: "kw", v: "const" }, { t: "plain", v: " report = " }, { t: "kw", v: "await" }, { t: "fn", v: " analyze" }, { t: "plain", v: "(suite);" }] },
      { indent: 0, tokens: [] },
      { indent: 1, tokens: [{ t: "kw", v: "if" }, { t: "plain", v: " (report.coverage < " }, { t: "num", v: "80" }, { t: "plain", v: ") {" }] },
      { indent: 2, tokens: [{ t: "kw", v: "const" }, { t: "plain", v: " tests = " }, { t: "kw", v: "await" }, { t: "fn", v: " report.generate" }, { t: "plain", v: "();" }] },
      { indent: 2, tokens: [{ t: "kw", v: "return" }, { t: "plain", v: " { tests, coverage: " }, { t: "num", v: "100" }, { t: "plain", v: " };" }] },
      { indent: 1, tokens: [{ t: "plain", v: "}" }] },
      { indent: 0, tokens: [{ t: "plain", v: "}" }] },
    ],
    highlight: [3, 4, 7, 8],
  },
  {
    lines: [
      { indent: 0, tokens: [{ t: "cmt", v: "// ✦ Generated by TestCovAI" }] },
      { indent: 0, tokens: [{ t: "fn", v: "describe" }, { t: "plain", v: "(" }, { t: "str", v: "'checkout function'" }, { t: "plain", v: ", () => {" }] },
      { indent: 1, tokens: [{ t: "fn", v: "it" }, { t: "plain", v: "(" }, { t: "str", v: "'throws on empty cart'" }, { t: "plain", v: ", () => {" }] },
      { indent: 2, tokens: [{ t: "fn", v: "expect" }, { t: "plain", v: "(() => " }, { t: "fn", v: "checkout" }, { t: "plain", v: "([], user))" }] },
      { indent: 2, tokens: [{ t: "plain", v: "  ." }, { t: "fn", v: "toThrow" }, { t: "plain", v: "(" }, { t: "str", v: "'Cart is empty'" }, { t: "plain", v: ");" }] },
      { indent: 1, tokens: [{ t: "plain", v: "});" }] },
      { indent: 0, tokens: [] },
      { indent: 1, tokens: [{ t: "fn", v: "it" }, { t: "plain", v: "(" }, { t: "str", v: "'processes valid payment'" }, { t: "plain", v: ", " }, { t: "kw", v: "async" }, { t: "plain", v: " () => {" }] },
      { indent: 2, tokens: [{ t: "kw", v: "const" }, { t: "plain", v: " result = " }, { t: "kw", v: "await" }, { t: "fn", v: " checkout" }, { t: "plain", v: "(cart, user);" }] },
      { indent: 2, tokens: [{ t: "fn", v: "expect" }, { t: "plain", v: "(result.status)." }, { t: "fn", v: "toBe" }, { t: "plain", v: "(" }, { t: "str", v: "'success'" }, { t: "plain", v: ");" }] },
      { indent: 1, tokens: [{ t: "plain", v: "});" }] },
      { indent: 0, tokens: [{ t: "plain", v: "});" }] },
    ],
    highlight: [2, 3, 4, 5, 7, 8, 9, 10],
  },
];

const TOKEN_COLORS = {
  kw:    "#ff7b72",
  fn:    "#d2a8ff",
  str:   "#a5d6ff",
  num:   "#79c0ff",
  cmt:   "#8b949e",
  id:    "#ffa657",
  plain: "#c9d1d9",
};

function renderTokens(tokens) {
  return tokens.map((tok, i) => (
    <span key={i} style={{ color: TOKEN_COLORS[tok.t] }}>
      {tok.v}
    </span>
  ));
}

export default function CodePreview() {
  const [frameIdx, setFrameIdx] = useState(0);
  const [visibleLines, setVisibleLines] = useState(0);

  const frame = CODE_FRAMES[frameIdx];

  // Cycle frames
  useEffect(() => {
    const t = setInterval(() => {
      setFrameIdx((f) => (f + 1) % CODE_FRAMES.length);
      setVisibleLines(0);
    }, 7000);
    return () => clearInterval(t);
  }, []);

  // Type lines one by one
  useEffect(() => {
    setVisibleLines(0);
    const lines = frame.lines;
    let i = 0;
    const t = setInterval(() => {
      i++;
      setVisibleLines(i);
      if (i >= lines.length) clearInterval(t);
    }, 90);
    return () => clearInterval(t);
  }, [frameIdx, frame.lines]);

  return (
    <div
      style={{
        position: "relative",
        borderRadius: "14px",
        overflow: "hidden",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#0D1117",
        boxShadow:
          "0 0 40px rgba(124,58,237,0.15), 0 0 80px rgba(124,58,237,0.05), 0 32px 64px rgba(0,0,0,0.5)",
        maxWidth: "540px",
        width: "100%",
      }}
    >
      {/* Title bar */}
      <div
        style={{
          background: "#161b22",
          padding: "0.625rem 1rem",
          display: "flex",
          alignItems: "center",
          gap: "0.75rem",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
        }}
      >
        <div style={{ display: "flex", gap: "6px" }}>
          {["#ef4444", "#fbbf24", "#4ade80"].map((c) => (
            <div
              key={c}
              style={{
                width: "10px",
                height: "10px",
                borderRadius: "50%",
                background: c,
                opacity: 0.7,
              }}
            />
          ))}
        </div>
        <AnimatePresence mode="wait">
          <motion.span
            key={frameIdx}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            style={{
              fontSize: "0.72rem",
              color: "#8b949e",
              fontFamily: "monospace",
              flex: 1,
              textAlign: "center",
            }}
          >
            {frameIdx === 0 ? "coverage.analysis.js" : "checkout.test.js"}
          </motion.span>
        </AnimatePresence>
        <span
          style={{
            fontSize: "0.62rem",
            padding: "2px 6px",
            borderRadius: "4px",
            background: "rgba(124,58,237,0.2)",
            color: "#9d5cf5",
            fontFamily: "monospace",
          }}
        >
          AI
        </span>
      </div>

      {/* Code body */}
      <div
        style={{
          padding: "1rem 0",
          minHeight: "260px",
          fontFamily: "monospace",
          fontSize: "0.78rem",
          lineHeight: "1.75",
        }}
      >
        <AnimatePresence mode="wait">
          <motion.div
            key={frameIdx}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
          >
            {frame.lines.slice(0, visibleLines).map((line, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, x: -8 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.15 }}
                style={{
                  display: "flex",
                  alignItems: "center",
                  background: frame.highlight.includes(idx)
                    ? "rgba(124,58,237,0.08)"
                    : "transparent",
                  borderLeft: frame.highlight.includes(idx)
                    ? "2px solid rgba(124,58,237,0.5)"
                    : "2px solid transparent",
                  padding: "0 1rem",
                }}
              >
                {/* Line number */}
                <span
                  style={{
                    color: "#30363d",
                    width: "28px",
                    userSelect: "none",
                    flexShrink: 0,
                    textAlign: "right",
                    marginRight: "12px",
                    fontSize: "0.68rem",
                  }}
                >
                  {idx + 1}
                </span>
                {/* Indent */}
                <span style={{ whiteSpace: "pre" }}>
                  {"  ".repeat(line.indent)}
                </span>
                {/* Tokens */}
                {renderTokens(line.tokens)}
                {/* Cursor on last visible line */}
                {idx === visibleLines - 1 && visibleLines < frame.lines.length && (
                  <motion.span
                    animate={{ opacity: [1, 0] }}
                    transition={{ duration: 0.5, repeat: Infinity }}
                    style={{
                      display: "inline-block",
                      width: "2px",
                      height: "14px",
                      background: "#7C3AED",
                      marginLeft: "2px",
                      verticalAlign: "middle",
                    }}
                  />
                )}
              </motion.div>
            ))}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* AI Active badge */}
      <motion.div
        animate={{ opacity: [0.7, 1, 0.7] }}
        transition={{ duration: 2, repeat: Infinity }}
        style={{
          position: "absolute",
          bottom: "12px",
          right: "12px",
          display: "flex",
          alignItems: "center",
          gap: "6px",
          padding: "5px 10px",
          borderRadius: "20px",
          background: "rgba(124,58,237,0.15)",
          border: "1px solid rgba(124,58,237,0.3)",
          backdropFilter: "blur(8px)",
          fontSize: "0.68rem",
          fontWeight: "600",
          color: "#9d5cf5",
        }}
      >
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
        >
          <Sparkles size={11} color="#9d5cf5" />
        </motion.div>
        AI Active
      </motion.div>

      {/* Coverage pill */}
      <div
        style={{
          position: "absolute",
          top: "44px",
          right: "12px",
          display: "flex",
          flexDirection: "column",
          gap: "4px",
          padding: "8px",
          borderRadius: "8px",
          background: "rgba(13,17,23,0.9)",
          border: "1px solid rgba(255,255,255,0.06)",
        }}
      >
        {[
          { label: "Stmts", v: 92, color: "#4ade80" },
          { label: "Branch", v: 78, color: "#fbbf24" },
          { label: "Funcs", v: 100, color: "#22d3ee" },
        ].map((item) => (
          <div key={item.label} style={{ display: "flex", alignItems: "center", gap: "6px" }}>
            <span style={{ fontSize: "0.6rem", color: "#484f58", width: "34px" }}>
              {item.label}
            </span>
            <div style={{ width: "60px", height: "3px", borderRadius: "2px", background: "rgba(255,255,255,0.06)" }}>
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${item.v}%` }}
                transition={{ duration: 1.2, ease: "easeOut" }}
                style={{ height: "100%", borderRadius: "2px", background: item.color }}
              />
            </div>
            <span style={{ fontSize: "0.6rem", color: item.color }}>{item.v}%</span>
          </div>
        ))}
      </div>
    </div>
  );
}
