@baseUrl = http://localhost:5000/api

### Auth
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "dinh@gmail.com",
  "password": "password123",
  "name": "dinh"
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "dinh@gmail.com",
  "password": "password123"
}

###
# @name forgotPassword
POST {{baseUrl}}/auth/forgotPassword
Content-Type: application/json

{
  "email": "huynhtandinh.dev@gmail.com"
}

###
# @name resetPassword
# Dán token sau resetPassword/
POST {{baseUrl}}/auth/resetPassword/1484ff0f9c5669498d52120db3c7741d81ea93eface28ec6f53a082f11e2b023
Content-Type: application/json

{
  "newPassword": "newPassword123"
}

### User
# @name getMe
# Dán token sau Bearer
GET {{baseUrl}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MDM3dXcwMDAwNG9idms5bWo2cTN0IiwidXNlckVtYWlsIjoiaHV5bmh0YW5kaW5oLmRldkBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODExNTcxODksImV4cCI6MTc4MTE2MDc4OX0.ELXzyTI8LNGvHB9qWMscILSMVGFEADGt6Ue5MwGioGU

### Projects
# @name createProject
POST {{baseUrl}}/projects
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "name": "My New Project"
}

###
# @name listProjects
GET {{baseUrl}}/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODY2MzUyMDksImV4cCI6MTc4NjYzODgwOX0.NkJKvtzCmY3VPfW7ucyFvxkxXVsuPdt-vOcFiGUZ6_8

###
# @name getProjectById
GET {{baseUrl}}/projects/YOUR_PROJECT_ID
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name deleteProject
DELETE {{baseUrl}}/projects/YOUR_PROJECT_ID
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name uploadZip
POST {{baseUrl}}/projects/YOUR_PROJECT_ID/upload-zip
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name
###
# @name getGithubAuthUrl
# Lưu ý: Thay YOUR_CLIENT_ID bằng ID thực tế của bạn, truy cập vào link bên dưới để lấy code xác thực
# https://github.com/login/oauth/authorize?client_id=Ov23liQyAORXbj6NeqAB&scope=user:email,repo
# @name githubCallback
# Sau khi lấy code thì tự động fallback về api Get bên dưới với tham số code để lấy access token
# GET {{baseUrl}}/auth/github/callback?code=CODE

###
# @name githubOAuthAccess
# Cái này cho việc bật/tắt truy cập vào private repository
POST {{baseUrl}}/auth/github/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MWs0d3YwMDAxNG9idjEyczBmNWZ1IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MTE4NDg4NiwiZXhwIjoxNzgxMTg4NDg2fQ.KHbVwR2vx3XiE6_idKUBBuxTjt_wbBfHMDWtxZFAvls
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MWs0d3YwMDAxNG9idjEyczBmNWZ1IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MTE4NDg4NiwiZXhwIjoxNzgxMTg4NDg2fQ.KHbVwR2vx3XiE6_idKUBBuxTjt_wbBfHMDWtxZFAvls",
  "allowAccess": "yes"
}

###
# @name listGithubRepositories
GET {{baseUrl}}/auth/github/repositories
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name cloneGithubRepositoryByUrl
POST {{baseUrl}}/projects/YOUR_PROJECT_ID/import-github-url
Content-Type: application/json

{
  "url": "https://github.com/owner/repo"
}

###
# @name importGithubRepository
POST {{baseUrl}}/projects/YOUR_PROJECT_ID/import-github-repo
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "owner": "owner_name",
  "repo": "repo_name"
}


### Lấy danh sách thông báo
# @name listNotifications
GET {{baseUrl}}/notifications?page=1&limit=10&unreadOnly=false
Authorization: Bearer YOUR_TOKEN_HERE

### Đánh dấu tất cả là đã đọc
# @name markAllNotificationsAsRead
PATCH {{baseUrl}}/notifications/read-all
Authorization: Bearer YOUR_TOKEN_HERE

### Đánh dấu 1 thông báo là đã đọc
# @name markNotificationAsRead
PATCH {{baseUrl}}/notifications/NHAP_ID_THONG_BAO_VAO_DAY/read
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name buildCfg
POST {{baseUrl}}/projects/cmquk92q20000r4bv21vc5n6b/cfg/build
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MWs0d3YwMDAxNG9idjEyczBmNWZ1IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MjQ1ODAwMywiZXhwIjoxNzgyNDYxNjAzfQ.S6tULiOqHRQFLBH4InmEft0PSnFh5N5m2ZEX2TyEOPs
Content-Type: application/json

{
  "snapshotId": "cmquk96tw0001r4bvl5hetv1c"
}

###
# @name getCfg
GET {{baseUrl}}/projects/cmquk92q20000r4bv21vc5n6b/cfg?snapshotId=cmquk96tw0001r4bvl5hetv1c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MWs0d3YwMDAxNG9idjEyczBmNWZ1IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MjQ1ODAwMywiZXhwIjoxNzgyNDYxNjAzfQ.S6tULiOqHRQFLBH4InmEft0PSnFh5N5m2ZEX2TyEOPs


###
# @name runAiTests
POST {{baseUrl}}/projects//ai-tests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF4cHd4dDEwMDAwbjBidjVlMnl1NHc0IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MjY1NjY0OSwiZXhwIjoxNzgyNjYwMjQ5fQ.r8NBnK1Mx4asRp2UOTb0Mn6JtgcgkI75iUS1IbT6qL0
Content-Type: application/json

{
  "snapshotId": "cmqxpxbx70002n0bvoxxqmf6x"
}

### AI Tests
# @name listAiTests
GET {{baseUrl}}/ai-tests?projectId=cmqxpx9a40001n0bvrkj0vlk7&page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF4cHd4dDEwMDAwbjBidjVlMnl1NHc0IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MjY1NjY0OSwiZXhwIjoxNzgyNjYwMjQ5fQ.r8NBnK1Mx4asRp2UOTb0Mn6JtgcgkI75iUS1IbT6qL0

### 
# @name GenerateFullTest
POST {{baseUrl}}/projects/cmqxpx9a40001n0bvrkj0vlk7/ai/generate-full-test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF4cHd4dDEwMDAwbjBidjVlMnl1NHc0IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MjY1NjY0OSwiZXhwIjoxNzgyNjYwMjQ5fQ.r8NBnK1Mx4asRp2UOTb0Mn6JtgcgkI75iUS1IbT6qL0
Content-Type: application/json

{
  "snapshotId": "cmqxpxbx70002n0bvoxxqmf6x"
}

###
# @name getAiTests
GET {{baseUrl}}/projects/cmqxpx9a40001n0bvrkj0vlk7/ai/tests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF4cHd4dDEwMDAwbjBidjVlMnl1NHc0IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MjY1NjY0OSwiZXhwIjoxNzgyNjYwMjQ5fQ.r8NBnK1Mx4asRp2UOTb0Mn6JtgcgkI75iUS1IbT6qL0

//Quy
###
# @name getNotifications
GET {{baseUrl}}/notifications?page=1&limit=10&unreadOnly=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODI5MTIwMjUsImV4cCI6MTc4MjkxNTYyNX0.di2MoUU5mZAvtOSpP2nKh3cefBvc--6vzhdhx79fe24

###
# @name getUnreadCount
GET {{baseUrl}}/notifications?unreadOnly=true
Authorization: Bearer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODI5MTI1NjcsImV4cCI6MTc4MjkxNjE2N30.T8dc_ojwEpWwgnUhgdZKjrBvbbWJt64rW3PKuZTBV60

###
# @name getUnreadCount
GET {{baseUrl}}/notifications/unread-count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODI5MTI1NjcsImV4cCI6MTc4MjkxNjE2N30.T8dc_ojwEpWwgnUhgdZKjrBvbbWJt64rW3PKuZTBV60

###
# @name markNotificationAsRead
PATCH {{baseUrl}}/notifications/cmqyryx2000008cw5kqjbv2hz/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODI5MTI1NjcsImV4cCI6MTc4MjkxNjE2N30.T8dc_ojwEpWwgnUhgdZKjrBvbbWJt64rW3PKuZTBV60

###
# @name markAllNotificationsAsRead
PATCH {{baseUrl}}/notifications/read-all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODI5MTIwMjUsImV4cCI6MTc4MjkxNTYyNX0.di2MoUU5mZAvtOSpP2nKh3cefBvc--6vzhdhx79fe24

###
# @name createNotification

POST {{baseUrl}}/notifications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODI3MDk4MTcsImV4cCI6MTc4MjcxMzQxN30.56SAdaMFYsszpa9IIsK49DatLXLJ_YWU5RerMDnxpXs

{
  "type": "SYSTEM",
  "title": "Test notification",
  "message": "Hello world"
}

### Analytics
# @name getDashboardAnalytics
GET {{baseUrl}}/analytics/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODMyMjM3ODAsImV4cCI6MTc4MzIyNzM4MH0.z6cjre0WXD8RhQY1CiwDNXDafhWezLhEUeerBJMHmB8

###
# @name detectVitest
POST {{baseUrl}}/projects/cmspgg2bo000016lmak0v5grh/detect-vitest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODY3Nzg1MjgsImV4cCI6MTc4Njc3OTQyOH0.fPK1-uSbbIqkTpsVVkTOlDF5ThVhefEC80nqsO6Ejow

### Chạy Vitest Tests
# @name runVitest
POST {{baseUrl}}/projects/cmsg1btlh00000vptmnj472y3/run-vitest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODY4MDkwNzgsImV4cCI6MTc4NjgwOTk3OH0.SqDVz2z1yXYJpPnJ-vbGsSN_20N5LIQOkQdu9CB7vqY
Content-Type: application/json

{
  "snapshotId": "cmsg1c66q00010vpt28gzunxv"
}

### Run Vitest Coverage
# @name runVitestCoverage
POST {{baseUrl}}/projects/cmsg1btlh00000vptmnj472y3/vitest-coverage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXF2cXplcGgwMDAwdXc3ZGw2MzIyNDhsIiwidXNlckVtYWlsIjoiZGluaEBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODY5ODIyNTAsImV4cCI6MTc4NzU4NzA1MH0.LVWaH14kQxjUeF2QwWjqjYCIhCOPAh5s3V2NvRIesas
Content-Type: application/json

{
  "snapshotId": "cmsg1c66q00010vpt28gzunxv"
}

### Run Playwright Detection
# @name detectPlaywright
POST {{baseUrl}}/projects/cmsg1btlh00000vptmnj472y3/playwright-detection
Authorization: Bearer 
