@baseUrl = http://localhost:5000/api

### Auth
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "dinh@gmail.com",
  "password": "password123",
  "name": "dinh"
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "huynhtandinh.dev@gmail.com",
  "password": "newPassword123"
}

###
# @name forgotPassword
POST {{baseUrl}}/auth/forgotPassword
Content-Type: application/json

{
  "email": "huynhtandinh.dev@gmail.com"
}

###
# @name resetPassword
# Dán token sau resetPassword/
POST {{baseUrl}}/auth/resetPassword/1484ff0f9c5669498d52120db3c7741d81ea93eface28ec6f53a082f11e2b023
Content-Type: application/json

{
  "newPassword": "newPassword123"
}

### User
# @name getMe
# Dán token sau Bearer
GET {{baseUrl}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MDM3dXcwMDAwNG9idms5bWo2cTN0IiwidXNlckVtYWlsIjoiaHV5bmh0YW5kaW5oLmRldkBnbWFpbC5jb20iLCJ1c2VyTmFtZSI6ImRpbmgiLCJpYXQiOjE3ODExNTcxODksImV4cCI6MTc4MTE2MDc4OX0.ELXzyTI8LNGvHB9qWMscILSMVGFEADGt6Ue5MwGioGU

### Projects
# @name createProject
POST {{baseUrl}}/projects
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "name": "My New Project"
}

###
# @name listProjects
GET {{baseUrl}}/projects
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name getProjectById
GET {{baseUrl}}/projects/YOUR_PROJECT_ID
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name deleteProject
DELETE {{baseUrl}}/projects/YOUR_PROJECT_ID
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name uploadZip
POST {{baseUrl}}/projects/YOUR_PROJECT_ID/upload-zip
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name
###
# @name getGithubAuthUrl
# Lưu ý: Thay YOUR_CLIENT_ID bằng ID thực tế của bạn, truy cập vào link bên dưới để lấy code xác thực
# https://github.com/login/oauth/authorize?client_id=Ov23liQyAORXbj6NeqAB&scope=user:email,repo
# @name githubCallback
# Sau khi lấy code thì tự động fallback về api Get bên dưới với tham số code để lấy access token
# GET {{baseUrl}}/auth/github/callback?code=CODE

###
# @name githubOAuthAccess
# Cái này cho việc bật/tắt truy cập vào private repository
POST {{baseUrl}}/auth/github/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MWs0d3YwMDAxNG9idjEyczBmNWZ1IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MTE4NDg4NiwiZXhwIjoxNzgxMTg4NDg2fQ.KHbVwR2vx3XiE6_idKUBBuxTjt_wbBfHMDWtxZFAvls
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXE5MWs0d3YwMDAxNG9idjEyczBmNWZ1IiwidXNlckVtYWlsIjoiaHV5bmhkaW5oMms1MjcwN0BnbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkRpbmhHSCIsImlhdCI6MTc4MTE4NDg4NiwiZXhwIjoxNzgxMTg4NDg2fQ.KHbVwR2vx3XiE6_idKUBBuxTjt_wbBfHMDWtxZFAvls",
  "allowAccess": "yes"
}

###
# @name listGithubRepositories
GET {{baseUrl}}/auth/github/repositories
Authorization: Bearer YOUR_TOKEN_HERE

###
# @name cloneGithubRepositoryByUrl
POST {{baseUrl}}/projects/YOUR_PROJECT_ID/import-github-url
Content-Type: application/json

{
  "url": "https://github.com/owner/repo"
}

###
# @name importGithubRepository
POST {{baseUrl}}/projects/YOUR_PROJECT_ID/import-github-repo
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "owner": "owner_name",
  "repo": "repo_name"
}

###
# @name runAiTests
POST {{baseUrl}}/projects//ai-tests
Authorization: Bearer 
Content-Type: application/json

{
  "snapshotId": ""
}
