ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'VITEST_COVERAGE';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'CYPRESS_SYSTEM_TEST';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'CYPRESS_SYSTEM_COVERAGE';
ALTER TYPE "TestType" ADD VALUE IF NOT EXISTS 'VITEST';
