import prisma from "../config/prisma.js";
import { getJobById, addJobLog } from "./job.service.js";
import { updateJobStatus } from "./jobUpdate.service.js";
import { buildAiPayload } from "./aiContextBuilder.service.js";
import { buildFinalPrompt } from "./aiPromptBuilder.service.js";
import { generateText } from "./gemini.service.js";
import { processAiSuggestions } from "./aiSuggestionParser.service.js";

/**
 * Orchestrates the full AI Suggestion Pipeline
 */
export const processAiSuggestJob = async (jobId) => {
    try {
        const job = await getJobById(jobId);

        // SCRUM-309: Update job status
        await updateJobStatus({
            jobId,
            status: "RUNNING",
            progress: 5,
        });

        const { snapshotId, projectId } = job;

        // SCRUM-307: Build context
        await addJobLog(jobId, "INFO", "Building AI Context Payload...");
        const payload = await buildAiPayload(snapshotId);
        
        await updateJobStatus({ jobId, progress: 30 });

        // Build Prompt
        await addJobLog(jobId, "INFO", "Constructing final prompt...");
        // Assuming we want FULL mode testing by default, but it can be configured
        const finalPrompt = buildFinalPrompt(payload, { mode: "FULL" });
        
        await updateJobStatus({ jobId, progress: 40 });

        // SCRUM-312: Call Gemini
        await addJobLog(jobId, "INFO", "Calling Gemini AI model...");
        const responseText = await generateText(finalPrompt, "gemini-1.5-pro");
        
        if (!responseText) {
            throw new Error("Gemini returned an empty response.");
        }

        await updateJobStatus({ jobId, progress: 80 });

        // SCRUM-311: Parse response
        await addJobLog(jobId, "INFO", "Parsing AI response...");
        const suggestions = processAiSuggestions(responseText, projectId, snapshotId);

        // SCRUM-310: Save suggestions
        await addJobLog(jobId, "INFO", "Saving suggestions to database...");
        
        // Remove existing suggestions for this snapshot to prevent duplicates
        await prisma.aiSuggestion.deleteMany({
            where: { snapshotId }
        });

        if (suggestions.length > 0) {
            await prisma.aiSuggestion.createMany({
                data: suggestions
            });
            await addJobLog(jobId, "INFO", `Saved ${suggestions.length} suggestions.`);
        } else {
            await addJobLog(jobId, "INFO", "No suggestions were generated by the AI.");
        }

        await updateJobStatus({
            jobId,
            status: "SUCCESS",
            progress: 100,
        });

        return { success: true, count: suggestions.length };
    } catch (error) {
        console.error(`[AiSuggestJob ${jobId}] Failed:`, error);
        
        await addJobLog(jobId, "ERROR", `Pipeline Error: ${error.message}`);
        
        await updateJobStatus({
            jobId,
            status: "FAILED",
            errorMessage: error.message,
        });

        throw error;
    }
};
