import fs from "fs";
import path from "path";
import prisma from "../config/prisma.js";
import { ServiceError } from "../utils/serviceError.js";

/**
 * SCRUM-85: Coverage Summary Parser
 *
 * Parse coverage-summary.json generated by Jest and save to DB:
 *  - SCRUM-118: Parse line coverage
 *  - SCRUM-119: Parse branch coverage
 *  - SCRUM-120: Parse function coverage
 *  - SCRUM-121: Parse statement coverage
 *  - SCRUM-122: Create/update CoverageSummary record
 */

/**
 * Read and validate coverage-summary.json file from coverageDir.
 * Returns parsed raw object.
 */
const readCoverageSummaryFile = (coverageDir) => {
    const summaryPath = path.join(coverageDir, "coverage-summary.json");

    if (!fs.existsSync(summaryPath)) {
        throw new ServiceError(
            `coverage-summary.json not found at: ${summaryPath}`,
            404
        );
    }

    let raw;
    try {
        raw = JSON.parse(fs.readFileSync(summaryPath, "utf8"));
    } catch (err) {
        throw new ServiceError(`Unable to parse coverage-summary.json: ${err.message}`, 422);
    }

    if (!raw || typeof raw !== "object") {
        throw new ServiceError("Invalid coverage-summary.json (empty or not an object)", 422);
    }

    if (!raw.total) {
        throw new ServiceError("coverage-summary.json missing 'total' field", 422);
    }

    return raw;
};

const parsePct = (val) => {
    if (val === 'Unknown') return 0;
    if (typeof val === "number" && !isNaN(val)) return val;
    if (typeof val === "string") {
        const parsed = parseFloat(val);
        if (!isNaN(parsed)) return parsed;
    }
    return 0;
};

const parseNum = (val) => {
    if (typeof val === "number" && !isNaN(val)) return val;
    if (typeof val === "string") {
        const parsed = parseInt(val, 10);
        if (!isNaN(parsed)) return parsed;
    }
    return 0;
};

const parseMetricEntry = (metric) => {
    const total = parseNum(metric?.total);
    const covered = parseNum(metric?.covered);
    const skipped = parseNum(metric?.skipped);
    let pct = parsePct(metric?.pct);
    if (total === 0 && covered === 0) {
        pct = 0;
    }
    return { total, covered, skipped, pct };
};

/**
 * SCRUM-118: Parse line coverage from a Jest entry
 */
const parseLineCoverage = (entry) => parseMetricEntry(entry?.lines);

/**
 * SCRUM-119: Parse branch coverage from a Jest entry
 */
const parseBranchCoverage = (entry) => parseMetricEntry(entry?.branches);

/**
 * SCRUM-120: Parse function coverage from a Jest entry
 */
const parseFunctionCoverage = (entry) => parseMetricEntry(entry?.functions);

/**
 * SCRUM-121: Parse statement coverage from a Jest entry
 */
const parseStatementCoverage = (entry) => parseMetricEntry(entry?.statements);

/**
 * SCRUM-122: Create or update CoverageSummary record in DB.
 */
const upsertCoverageSummary = async (snapshotId, lines, branches, functions, statements) => {
    let l = parsePct(lines?.pct ?? lines);
    let b = parsePct(branches?.pct ?? branches);
    let f = parsePct(functions?.pct ?? functions);
    let s = parsePct(statements?.pct ?? statements);

    if (lines?.total === 0 && statements?.total === 0) {
        l = 0;
        b = 0;
        f = 0;
        s = 0;
    }

    return prisma.coverageSummary.upsert({
        where: { snapshotId },
        create: {
            snapshotId,
            linesPct: l,
            branchesPct: b,
            funcsPct: f,
            stmtsPct: s,
        },
        update: {
            linesPct: l,
            branchesPct: b,
            funcsPct: f,
            stmtsPct: s,
        },
    });
};

/**
 * Upsert CoverageFile records for each project file.
 */
const upsertCoverageFiles = async (snapshotId, fileEntries) => {
    for (const [filePath, data] of fileEntries) {
        const lines = parseLineCoverage(data);
        const branches = parseBranchCoverage(data);
        const functions = parseFunctionCoverage(data);
        const statements = parseStatementCoverage(data);

        await prisma.coverageFile.upsert({
            where: { snapshotId_filePath: { snapshotId, filePath } },
            create: {
                snapshotId,
                filePath,
                linesPct: parsePct(lines?.pct),
                branchesPct: parsePct(branches?.pct),
                funcsPct: parsePct(functions?.pct),
                stmtsPct: parsePct(statements?.pct),
            },
            update: {
                linesPct: parsePct(lines?.pct),
                branchesPct: parsePct(branches?.pct),
                funcsPct: parsePct(functions?.pct),
                stmtsPct: parsePct(statements?.pct),
            },
        });
    }
};

/**
 * Main entry point of SCRUM-85.
 *
 * Reads coverage-summary.json → parses each coverage type →
 * persists CoverageSummary + CoverageFile into DB.
 *
 * @param {string} coverageDir  - Path to the coverage/ directory (generated by jest)
 * @param {string} snapshotId   - ID of ProjectSnapshot
 * @returns {{ summary, total, fileCount }}
 */
export const parseCoverageSummary = async (coverageDir, snapshotId) => {
    if (!coverageDir || !snapshotId) {
        throw new ServiceError("coverageDir and snapshotId are required", 400);
    }

    // Read file
    const raw = readCoverageSummaryFile(coverageDir);

    // Parse overall summary metrics
    const total = raw.total;
    const lines = parseLineCoverage(total);       // SCRUM-118
    const branches = parseBranchCoverage(total);  // SCRUM-119
    const functions = parseFunctionCoverage(total); // SCRUM-120
    const statements = parseStatementCoverage(total); // SCRUM-121

    // SCRUM-122: Ghi CoverageSummary
    const summary = await upsertCoverageSummary(snapshotId, lines, branches, functions, statements);

    // Write CoverageFile per file (excluding "total" key)
    const fileEntries = Object.entries(raw).filter(([key]) => key !== "total");
    await upsertCoverageFiles(snapshotId, fileEntries);

    return {
        summary,
        total: {
            lines,
            branches,
            functions,
            statements,
        },
        fileCount: fileEntries.length,
    };
};
