/**
 * Supertest Post Processor Service
 * Processes raw AI output into validated Supertest integration test records.
 */

/**
 * Removes markdown code block wrappers from content.
 * @param {string} content
 * @returns {string}
 */
export const removeMarkdownWrappers = (content) => {
    if (!content) return "";
    let cleaned = content;
    cleaned = cleaned.replace(/^```(json|javascript|js|ts|typescript)?\s*/i, "");
    cleaned = cleaned.replace(/```\s*$/i, "");
    return cleaned.trim();
};

/**
 * Parses the raw text output from the AI into a JSON object.
 * @param {string} text
 * @returns {object|null}
 */
export const parseSupertestResponse = (text) => {
    if (!text) return null;
    try {
        const cleaned = removeMarkdownWrappers(text);
        const parsed = JSON.parse(cleaned);
        return parsed;
    } catch (e) {
        console.error("[SupertestPostProcessor] Failed to parse AI JSON:", e.message);
        return null;
    }
};

/**
 * Validates that the AI parsed output has the expected Supertest JSON structure.
 * @param {any} parsedData
 * @returns {{ valid: boolean, errors: string[] }}
 */
export const validateSupertestOutputFormat = (parsedData) => {
    const errors = [];

    if (!parsedData || typeof parsedData !== "object") {
        errors.push("Parsed AI data must be a JSON object.");
        return { valid: false, errors };
    }

    if (!parsedData.tests || !Array.isArray(parsedData.tests)) {
        errors.push('"tests" must be an array.');
        return { valid: false, errors };
    }

    if (parsedData.tests.length === 0) {
        errors.push("AI output contains no test files.");
        return { valid: false, errors };
    }

    return { valid: errors.length === 0, errors };
};

/**
 * Processes a single raw test entry from the AI output.
 * @param {{ filePath: string, content: string }} rawTest
 * @param {{ projectId: string, snapshotId: string }} context
 * @returns {object|null} Processed test record or null if invalid
 */
export const processSingleSupertestTest = (rawTest, { projectId, snapshotId }) => {
    if (!rawTest || !rawTest.filePath || !rawTest.content) {
        console.warn("[SupertestPostProcessor] Skipping test entry with missing filePath or content.");
        return null;
    }

    let content = rawTest.content.trim();
    if (!content.includes("[AI GENERATED]")) {
        content = `// [AI GENERATED] This Integration test was automatically generated by CovAI.\n\n${content}`;
    }

    return {
        projectId,
        snapshotId,
        filePath: rawTest.filePath.trim(),
        mode: "FULL", // Persist as FULL to avoid Prisma enum errors
        content,
        metaJson: JSON.stringify({ framework: "SUPERTEST", status: "DRAFT", isValid: true }),
    };
};

/**
 * Main orchestrator: parses AI response text, validates format,
 * and returns classified results.
 *
 * @param {string} responseText - Raw AI text response from Gemini
 * @param {{ projectId: string, snapshotId: string }} context
 * @returns {{ allTests: object[], summary: object }}
 */
export const processSupertestTests = (responseText, context) => {
    const parsedData = parseSupertestResponse(responseText);

    const validation = validateSupertestOutputFormat(parsedData);
    if (!validation.valid) {
        console.error("[SupertestPostProcessor] Validation failed:", validation.errors);
        throw new Error(`AI generated invalid Supertest format: ${validation.errors.join(" ")}`);
    }

    const allTests = [];

    for (const rawTest of parsedData.tests) {
        const processed = processSingleSupertestTest(rawTest, context);
        if (processed) {
            let fileContent = processed.content;
            
            // Ensure test files use import if needed (hotfix for Gemini hallucinating require in ESM)
            if (fileContent.includes("require('supertest')")) {
                fileContent = fileContent.replace(/const (\w+) = require\('supertest'\);?/g, "import $1 from 'supertest';");
            }
            if (fileContent.includes("require(")) {
                fileContent = fileContent.replace(/const (\w+) = require\((['"])([^'"]+)(['"])\);?/g, "import $1 from $2$3$4;");
            }

            // ESM compatibility: jest global is not available in ESM mode.
            // Add `import { jest } from '@jest/globals'` if jest.mock/jest.fn/etc is used without importing jest.
            if (fileContent.match(/\bjest\.(mock|fn|spyOn|clearAllMocks|resetAllMocks|restoreAllMocks)\b/) &&
                !fileContent.includes("from '@jest/globals'") &&
                !fileContent.includes('from "@jest/globals"')) {
                // Find the position after the last import statement to insert the jest import
                const lines = fileContent.split('\n');
                let lastImportIndex = -1;
                for (let i = 0; i < lines.length; i++) {
                    if (lines[i].trimStart().startsWith('import ')) {
                        lastImportIndex = i;
                    }
                }
                const jestImport = "import { jest } from '@jest/globals';";
                if (lastImportIndex >= 0) {
                    lines.splice(lastImportIndex + 1, 0, jestImport);
                } else {
                    lines.unshift(jestImport);
                }
                fileContent = lines.join('\n');
            }

            processed.content = fileContent;
            allTests.push(processed);
        }
    }

    const summary = {
        totalFiles: allTests.length,
        message: `Generated ${allTests.length} Supertest integration test file(s).`
    };

    return { allTests, summary };
};
