import fs from "node:fs";
import path from "node:path";
import prisma from "../config/prisma.js";
import { containedPath } from "./fullSystemLifecycle.service.js";
import { collectSystemGenerationContext } from "./systemGenerationContext.service.js";
import { generateText } from "./gemini.service.js";
import { validateGeneratedTestCode } from "../validators/aiTestCode.validator.js";
import { extractSuitesAndScenarios } from "../utils/testFileParser.js";
import { ServiceError } from "../utils/serviceError.js";

/**
 * Extracts JSON or clean code from a Gemini text response.
 */
export const extractBoosterResponse = (rawResponse) => {
  let text = String(rawResponse || "").trim();
  const fence = text.match(/^```(?:json|javascript|js|typescript|ts)?\s*([\s\S]*?)```\s*$/i);
  if (fence) text = fence[1].trim();

  try {
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === "object") {
      return parsed;
    }
  } catch (_) {
    // If not JSON, check if it's pure JavaScript code block
    const codeMatch = text.match(/```(?:javascript|js|typescript|ts)?\s*([\s\S]*?)```/i);
    const code = codeMatch ? codeMatch[1].trim() : text;
    if (code) {
      return {
        optimizedCode: code,
        explanation: "Optimized test code generated by AI.",
      };
    }
  }

  throw new ServiceError("Failed to parse AI booster response", 422);
};

/**
 * Generates rule-based booster test scenarios when AI is unavailable or offline.
 */
export const generateFallbackBoosterScenarios = ({ framework, existingCode, routes = ["/"] }) => {
  const isPlaywright = framework === "playwright";
  const primaryRoute = routes[0] || "/";

  if (isPlaywright) {
    const newScenarios = `
  test('AI Boost: handles boundary conditions and UI edge states', async ({ page }) => {
    await page.goto('${primaryRoute}');
    // 1. Verify primary interactive view is visible
    const container = page.locator('main, #root, #app, [role="main"], body');
    await expect(container.first()).toBeVisible({ timeout: 10000 });

    // 2. Edge case: verify error notification elements render gracefully
    const alertElements = page.locator('.error, .alert, [role="alert"]');
    const alertCount = await alertElements.count();
    if (alertCount > 0) {
      await expect(alertElements.first()).toBeVisible();
    }
  });

  test('AI Boost: verifies input validation and graceful error recovery', async ({ page }) => {
    await page.goto('${primaryRoute}');
    // Check form inputs with empty/blank boundary values
    const inputs = page.locator('input:not([type="hidden"]), textarea');
    const inputCount = await inputs.count();
    if (inputCount > 0) {
      await inputs.first().fill('   ');
      const submitBtn = page.locator('button[type="submit"], button:has-text("Submit"), button:has-text("Save"), button:has-text("Search")');
      if (await submitBtn.count() > 0 && await submitBtn.first().isEnabled()) {
        await submitBtn.first().click();
        await expect(page.locator('body')).toBeVisible();
      }
    }
  });`;

    // Insert inside the last describe block if present, or append
    const lastCloseIndex = existingCode.lastIndexOf("});");
    if (lastCloseIndex > 0) {
      return existingCode.slice(0, lastCloseIndex) + newScenarios + "\n" + existingCode.slice(lastCloseIndex);
    }
    return existingCode + "\n" + newScenarios;
  } else {
    // Cypress fallback
    const newScenarios = `
  it('AI Boost: handles boundary conditions and UI edge states', () => {
    cy.visit('${primaryRoute}');
    cy.get('body').should('be.visible');
    cy.get('body').then(($body) => {
      if ($body.find('.error, .alert, [role="alert"]').length > 0) {
        cy.get('.error, .alert, [role="alert"]').should('be.visible');
      }
    });
  });

  it('AI Boost: verifies input validation and graceful error recovery', () => {
    cy.visit('${primaryRoute}');
    cy.get('body').then(($body) => {
      const inputs = $body.find('input:visible, textarea:visible');
      if (inputs.length > 0) {
        cy.wrap(inputs.first()).clear().type('   ');
      }
    });
    cy.get('body').should('be.visible');
  });`;

    const lastCloseIndex = existingCode.lastIndexOf("});");
    if (lastCloseIndex > 0) {
      return existingCode.slice(0, lastCloseIndex) + newScenarios + "\n" + existingCode.slice(lastCloseIndex);
    }
    return existingCode + "\n" + newScenarios;
  }
};

/**
 * Generates rule-based repair when AI is unavailable or offline.
 */
export const generateFallbackBreakpointFix = ({
  framework,
  existingCode,
  failureStep,
  failureCategory,
  failureCodeSnippet,
  domSnapshot,
}) => {
  let repairedCode = existingCode;
  let fixedStep = failureStep || "Resilient locator adjustment";

  // If locator timed out or element not found
  if (failureStep && failureCategory && ["TIMEOUT", "ELEMENT_NOT_FOUND"].includes(failureCategory)) {
    // Check if failureStep has a fragile click like page.click('#checkout') or page.click('button#checkout')
    const clickMatch = failureStep.match(/(?:page\s*\.\s*click\s*\(\s*|cy\s*\.\s*get\s*\(\s*)(['"`])([^'"`]+)\1/);
    if (clickMatch) {
      const originalSelector = clickMatch[2];
      const selectorWord = originalSelector.replace(/[^a-zA-Z0-9]/g, " ").trim().split(/\s+/).pop() || "action";

      if (framework === "playwright") {
        // Replace with resilient locator with fallback text search and explicit timeout
        const resilientStep = `await page.locator('${originalSelector}, button:has-text("${selectorWord}")').first().click({ timeout: 10000 })`;
        if (repairedCode.includes(failureStep)) {
          repairedCode = repairedCode.replace(failureStep, resilientStep);
          fixedStep = resilientStep;
        } else if (failureCodeSnippet && repairedCode.includes(failureCodeSnippet.replace(/^>\s*\d+\s*\|\s*/, "").trim())) {
          const rawLine = failureCodeSnippet.replace(/^>\s*\d+\s*\|\s*/, "").trim();
          repairedCode = repairedCode.replace(rawLine, resilientStep);
          fixedStep = resilientStep;
        }
      } else {
        // Cypress resilient click
        const resilientStep = `cy.get('${originalSelector}').should('be.visible').click({ force: true })`;
        if (repairedCode.includes(failureStep)) {
          repairedCode = repairedCode.replace(failureStep, resilientStep);
          fixedStep = resilientStep;
        }
      }
    }
  }

  // If assertion failed (e.g. expected exact text vs actual)
  if (failureCategory === "ASSERTION_FAILED" && failureStep) {
    if (framework === "playwright" && failureStep.includes("toHaveText(")) {
      const relaxed = failureStep.replace(/toHaveText\s*\(([^)]+)\)/, "toContainText($1)");
      if (repairedCode.includes(failureStep)) {
        repairedCode = repairedCode.replace(failureStep, relaxed);
        fixedStep = relaxed;
      }
    } else if (framework === "cypress" && failureStep.includes("have.text")) {
      const relaxed = failureStep.replace(/'have\.text'/, "'include.text'");
      if (repairedCode.includes(failureStep)) {
        repairedCode = repairedCode.replace(failureStep, relaxed);
        fixedStep = relaxed;
      }
    }
  }

  return {
    optimizedCode: repairedCode,
    fixedStep,
    explanation: `Applied targeted fix for ${failureCategory || "breakpoint"}: strengthened locator resilience and updated timing behavior.`,
  };
};

/**
 * Main service to optimize test cases using AI or intelligent rule-based engine.
 *
 * @param {Object} options
 * @param {string} options.rootDir - Snapshot repository root directory
 * @param {string} options.filePath - Relative path to target test file
 * @param {string} [options.scenarioId] - Optional scenario ID for breakpoint diagnosis
 * @param {string} [options.mode="BOOST_COVERAGE"] - "BOOST_COVERAGE" | "FIX_BREAKPOINT"
 * @param {string} [options.instruction] - Optional user guidance
 * @param {Object} [options.scenarioData] - Optional explicit scenario object (for testing)
 * @returns {Promise<Object>} Optimized code, explanation, and metadata
 */
export const optimizeSystemTest = async ({
  rootDir,
  filePath,
  scenarioId = null,
  mode = "BOOST_COVERAGE",
  instruction = null,
  scenarioData = null,
}) => {
  if (!rootDir || typeof rootDir !== "string") {
    throw new ServiceError("rootDir is required", 400);
  }
  if (!filePath || typeof filePath !== "string") {
    throw new ServiceError("filePath is required", 400);
  }

  const normalizedMode = String(mode).toUpperCase().trim();
  if (!["BOOST_COVERAGE", "FIX_BREAKPOINT"].includes(normalizedMode)) {
    throw new ServiceError("mode must be 'BOOST_COVERAGE' or 'FIX_BREAKPOINT'", 400);
  }

  const fullPath = containedPath(rootDir, filePath);
  if (!fs.existsSync(fullPath)) {
    throw new ServiceError(`Test file not found: ${filePath}`, 404);
  }

  const existingCode = fs.readFileSync(fullPath, "utf8");
  const isCypress =
    filePath.toLowerCase().includes("cypress") ||
    /\bcy\./.test(existingCode) ||
    /from\s+['"]cypress['"]/.test(existingCode);
  const framework = isCypress ? "cypress" : "playwright";

  let harvestedContext = {};
  try {
    harvestedContext = collectSystemGenerationContext(rootDir);
  } catch (_) {}

  const discoveredRoutes = harvestedContext.frontendContext?.routes || ["/"];
  const uiActions = harvestedContext.frontendContext?.uiActions || [];
  const clientApiCalls = harvestedContext.frontendContext?.clientApiCalls || [];

  if (normalizedMode === "BOOST_COVERAGE") {
    // ---------------------- MODE 1: BOOST COVERAGE ----------------------
    const systemPrompt = `You are an elite QA automation architect specialized in ${framework === "playwright" ? "Playwright" : "Cypress"}.
Your mission is to expand the existing test suite with high-value edge case scenarios (form validation errors, boundary conditions, empty states, and error handling) to achieve maximum branch, route, and component test coverage.
CRITICAL RULES:
1. Preserve all existing tests and imports exactly as they are.
2. Add 2 to 3 new distinctive test scenarios inside the existing describe/suite block.
3. Use realistic assertions checking DOM elements, error texts, and application state.
4. Do NOT import non-existent libraries or forbidden packages (eval, child_process).
5. Output response as JSON:
{
  "optimizedCode": "<full updated test file code>",
  "addedScenarios": ["scenario title 1", "scenario title 2"],
  "explanation": "<concise explanation of added coverage paths>"
}`;

    const userPrompt = `Target Test File: ${filePath}
Framework: ${framework}
Application Routes Discovered: ${JSON.stringify(discoveredRoutes)}
Interactive UI Elements: ${JSON.stringify(uiActions.slice(0, 10))}
API Calls: ${JSON.stringify(Array.from(clientApiCalls).slice(0, 10))}

${instruction ? `User Custom Guidance: ${instruction}\n` : ""}
Existing Test Code:
\`\`\`javascript
${existingCode}
\`\`\`

Generate the updated test file code with expanded scenarios to boost coverage.`;

    let optimizedResult = null;
    try {
      const aiResponse = await generateText(userPrompt, systemPrompt, {
        temperature: 0.2,
      });
      const parsed = extractBoosterResponse(aiResponse);
      if (parsed.optimizedCode) {
        validateGeneratedTestCode(parsed.optimizedCode);
        optimizedResult = {
          optimizedCode: parsed.optimizedCode,
          addedScenarios: Array.isArray(parsed.addedScenarios) ? parsed.addedScenarios : ["Edge case validation scenarios"],
          explanation: parsed.explanation || "Expanded test scenarios to cover edge cases and validation paths.",
        };
      }
    } catch (aiErr) {
      console.warn(`[systemTestBooster] AI model call warning (${aiErr.message}). Using intelligent rule-based booster.`);
    }

    if (!optimizedResult) {
      const fallbackCode = generateFallbackBoosterScenarios({
        framework,
        existingCode,
        routes: discoveredRoutes,
      });
      validateGeneratedTestCode(fallbackCode);
      optimizedResult = {
        optimizedCode: fallbackCode,
        addedScenarios: [
          "AI Boost: handles boundary conditions and UI edge states",
          "AI Boost: verifies input validation and graceful error recovery",
        ],
        explanation: "Injected boundary validation and empty state test scenarios to cover previously untested paths.",
      };
    }

    return {
      success: true,
      mode: "BOOST_COVERAGE",
      framework,
      filePath,
      optimizedCode: optimizedResult.optimizedCode,
      addedScenarios: optimizedResult.addedScenarios,
      explanation: optimizedResult.explanation,
    };
  } else {
    // ---------------------- MODE 2: FIX BREAKPOINT ----------------------
    let scenario = scenarioData;
    if (!scenario && scenarioId) {
      try {
        scenario = await prisma.testScenario.findUnique({
          where: { id: scenarioId },
        });
      } catch (_) {}
    }

    const failureStep = scenario?.failureStep || null;
    const failureCategory = scenario?.failureCategory || "BREAKPOINT_ERROR";
    const failureCodeSnippet = scenario?.failureCodeSnippet || null;
    const failureMessages = scenario?.failureMessages || [];
    const domSnapshot = scenario?.domSnapshot || null;

    const systemPrompt = `You are a senior test automation engineer specialized in fixing broken ${framework === "playwright" ? "Playwright" : "Cypress"} tests.
Your task is to repair the specific step/locator where the test failed.
CRITICAL RULES:
1. Fix the broken locator or assertion without altering the intended test goal.
2. Use robust, accessible locators (e.g. getByRole, button:has-text, data-testid) instead of brittle CSS selectors.
3. Account for element states (disabled, visible, attached) using proper waits.
4. Output response as JSON:
{
  "optimizedCode": "<full repaired test file code>",
  "fixedStep": "<the repaired line or step>",
  "explanation": "<root cause and fix explanation>"
}`;

    const userPrompt = `Target Test File: ${filePath}
Framework: ${framework}
Failed Scenario Title: ${scenario?.title || "Unknown"}
Failure Category: ${failureCategory}
Failure Step: ${failureStep || "N/A"}
Failure Code Snippet: ${failureCodeSnippet || "N/A"}
Error Messages: ${JSON.stringify(failureMessages)}
DOM Snapshot at Breakpoint: ${domSnapshot || "N/A"}

${instruction ? `User Custom Guidance: ${instruction}\n` : ""}
Existing Test Code:
\`\`\`javascript
${existingCode}
\`\`\`

Repair the broken step in the test code.`;

    let repairResult = null;
    try {
      const aiResponse = await generateText(userPrompt, systemPrompt, {
        temperature: 0.1,
      });
      const parsed = extractBoosterResponse(aiResponse);
      if (parsed.optimizedCode) {
        validateGeneratedTestCode(parsed.optimizedCode);
        repairResult = {
          optimizedCode: parsed.optimizedCode,
          fixedStep: parsed.fixedStep || failureStep || "Repaired selector",
          explanation: parsed.explanation || "Repaired fragile locator and adjusted wait conditions.",
        };
      }
    } catch (aiErr) {
      console.warn(`[systemTestBooster] AI model call warning (${aiErr.message}). Using intelligent rule-based fixer.`);
    }

    if (!repairResult) {
      repairResult = generateFallbackBreakpointFix({
        framework,
        existingCode,
        failureStep,
        failureCategory,
        failureCodeSnippet,
        domSnapshot,
      });
      validateGeneratedTestCode(repairResult.optimizedCode);
    }

    return {
      success: true,
      mode: "FIX_BREAKPOINT",
      framework,
      filePath,
      scenarioId,
      failureCategory,
      fixedStep: repairResult.fixedStep,
      optimizedCode: repairResult.optimizedCode,
      explanation: repairResult.explanation,
    };
  }
};

